name 'volgactf-2018-final-cloud'
description ''
version '1.0.0'

recipe 'volgactf-2018-final-cloud', ''
depends 'git'
depends 'git2', '~> 1.0.0'
depends 'poise-python', '~> 1.7.0'
depends 'supervisor', '~> 0.4.12'
depends 'nginx'
depends 'ssh-private-keys', '~> 2.0.0'
depends 'ssh_known_hosts'
depends 'instance', '~> 2.0.0'
depends 'secret', '~> 1.0.0'
depends 'postgresql', '~> 6.1.1'
depends 'database', '~> 6.1.1'
